---
title: "Acute analysis"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r}
#load the libraries
library(tidyverse)
library(lubridate)
library(knitr)
library(gmodels)
```

```{r}
#declare the variables

Column_names <- c(
  "Counter",
  "NHI",
  "Theatre",
  "Type",
  "Original_Ward",
  "Surgeon",
  "Surgeon_Teach",
  "Anaesthetist",
  "Anaesthetist_Teach",
  "Anaesthetic",
  "Anaesthetist_Risk",
  "Operation_Code",
  "Operation_Code_Extention",
  "PurchaserNumber",
  "Patient_Side",
  "Specialty_Over_ride",
  "Booking_In_Date",
  "Booking_In_Time",
  "Event_Date",
  "Arrival_In_Anaesthetic_Room",
  "Anaesthesia_Start",
  "Patient_Ready_for_Operation",
  "Operation_Start",
  "Operation_End",
  "Recovery_Takeover",
  "Patient_Opens_Eyes_On_Command",
  "Recovery_Complete",
  "Left_Recovery",
  "Anaesthetic_Time",
  "Operation_Time",
  "Scrub_Nurse",
  "Charge_Nurse",
  "Anaesthetic_Assist",
  "AnaestheticAssistTeach",
  "Problem_Code",
  "DirectMaterialCost",
  "Planned_Return",
  "SessionCode",
  "Verified",
  "Episode",
  "AdmissionType",
  "Modified",
  "ModifiedBy",
  "Processed",
  "Created",
  "EventComments",
  "TheatreOther",
  "PlannedOperation",
  "GRN",
  "Admission_Date",
  "AdmissionWard",
  "EpisodeWhole",
  "TimeOut",
  "UnplannedReturn",
  "Problem_Description",
  "Group_Description",
  "Specialty_Description",
  "SpecialtyCode",
  "Operation_Description"
)
```

```{r, messages = FALSE, warnings = FALSE}
#load the data

OTIS <- read_csv("/home/greig/R-projects/Clinical_audits/Theatre/OTIS_rawData.csv", col_names = Column_names, skip = 1)
```

```{r}
#transform the data

OTIS$Operation_Start <- as.character(OTIS$Operation_Start)
OTIS$Operation_End <- as.character(OTIS$Operation_End)

OTIS$Operation_Start <- paste(OTIS$Event_Date, OTIS$Operation_Start, sep = " ")
OTIS$Operation_End <- paste(OTIS$Event_Date, OTIS$Operation_End, sep = " ")
OTIS$Anaesthesia_Start <- paste(OTIS$Event_Date, OTIS$Anaesthesia_Start, sep = " ")
OTIS$Recovery_Takeover <- paste(OTIS$Event_Date, OTIS$Recovery_Takeover, sep = " ")

OTIS$Operation_Start <-  dmy_hms(OTIS$Operation_Start)
OTIS$Operation_End <- dmy_hms(OTIS$Operation_End)
OTIS$Anaesthesia_Start <- dmy_hms(OTIS$Anaesthesia_Start)
OTIS$Recovery_Takeover <- dmy_hms(OTIS$Recovery_Takeover)

OTIS$Surg_Span <- interval(OTIS$Operation_Start, OTIS$Operation_End)
OTIS$Surg_Span <- as.duration(OTIS$Surg_Span)
OTIS$Surg_Span <- as.integer(OTIS$Surg_Span)  / 60

OTIS$Anaes_Span <- interval(OTIS$Anaesthesia_Start, OTIS$Recovery_Takeover)
OTIS$Anaes_Span <- as.duration(OTIS$Anaes_Span)
OTIS$Anaes_Span <- as.integer(OTIS$Anaes_Span)  / 60

OTIS$Event_Date <- dmy(OTIS$Event_Date)

OTIS <- OTIS %>% 
  filter(0 < Surg_Span) %>% 
  filter(0 < Anaes_Span)

OTIS$AdmissionType <- as.factor(OTIS$AdmissionType)

OTIS$DOW <- wday(OTIS$Event_Date)
OTIS$Hour <- hour(OTIS$Anaesthesia_Start)
OTIS$Theatre <- as.factor(OTIS$Theatre)

OTIS$TOD <-  ifelse(8 <= OTIS$Hour & OTIS$Hour <= 17, "Daytime", "Afterhours" )
OTIS$TOD <- as.factor(OTIS$TOD)

glimpse(OTIS)
```

```{r}
#Acute theatre usage for Nov.2017

AcuteOT <- OTIS %>% 
  filter("2017-06-01" <= Event_Date & Event_Date <= "2017-06-30" & AdmissionType == "AC") %>% 
  filter(Theatre != "M" & Theatre != "O") %>% 
  filter(Anaes_Span < 400)

```

```{r}
#Histogram of acute cases per theatre

ggplot(data = AcuteOT) +
  geom_bar(aes(x = Theatre, fill = Theatre)) +
  labs(title = "Number of acute cases per theatre June.2017", x = "Theatre", y = "Count of Acute cases") +
  theme_minimal()
```

```{r}
#Histogram of acute cases by DOW

ggplot(data = AcuteOT) +
  geom_bar(aes(x = Hour), fill = "red") +
  labs(title = "Number of Acute case by hour of the day June.2017") +
  theme_minimal()
```

```{r}
#Histogram of acute cases by Hour of day & time of day

ggplot(data = AcuteOT, aes(x = Hour)) +
  geom_bar(aes(fill = TOD)) +
  labs(title = "Number of Acute case by hour of the day June.2017") +
  guides(fill = guide_legend(title = "Time of Day")) +
  theme_minimal()
```


```{r}
ggplot(data = AcuteOT, aes(x = Hour)) +
  geom_density(aes(fill = TOD)) +
  labs(title = "Density plot of Acute case by hour of the day June.2017") +
  guides(fill = guide_legend(title = "Time of Day")) +
  theme_minimal()
```

```{r}
AcuteDist <- AcuteOT %>% 
  group_by(TOD) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

kable(AcuteDist)
```


```{r}
#Histogram of acute case by day of week

ggplot(data = AcuteOT) +
  geom_bar(aes(x = DOW, fill = factor(DOW, labels = c("Sun", "Mon", "Tues", "Wed", "Thur", "Fri", "Sat")))) +
  labs(title = "Count of Acute cases by Day of Week, June.2017", x = "Day of week") +
  guides(fill = guide_legend(title = "Day of week")) +
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank())

```

```{r}
#By Subspec

SubSpec <- AcuteOT %>% 
  group_by(Specialty_Description) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

kable(SubSpec)
```

```{r}
#by SubSpec & DOW

SubSpec_DOW <- AcuteOT %>% 
  group_by(Specialty_Description, DOW) %>% 
  summarise(Count = n())

SubSpec_DOW <- spread(SubSpec_DOW, DOW, Count)
SubSpec_DOW <- SubSpec_DOW %>% 
  filter(Specialty_Description != "Gastroenterology" & Specialty_Description != "General Medicine" & Specialty_Description != "Pain Relief")

SubSpec_DOW
```


```{r}
AcuteCase <- AcuteOT %>% 
  group_by(Operation_Description) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

kable(head(AcuteCase, n = 10), format = "html", caption = "Top ten types of operation")
```

```{r}
AcuteDay <- AcuteOT %>% 
  filter(TOD == "Daytime") %>% 
  group_by(Operation_Description) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

kable(head(AcuteDay, n = 10), format = "html", caption = "Top ten types of acute operations during the day")
```

```{r}
AcuteNight <- AcuteOT %>% 
  filter(TOD == "Afterhours") %>% 
  group_by(Operation_Description) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

kable(head(AcuteNight, n = 10), format = "html", caption = "Top ten types of after hours acute operations")
```



```{r}
ggplot(AcuteOT) +
  geom_histogram(aes(Anaes_Span, fill = TOD), binwidth = 10) +
  labs(title = "Density plot of Case duration by time of the day June.2017", x = "Anaesathetic duration (Minutes)") +
  guides(fill = guide_legend(title = "Time of Day")) +
  theme_minimal()
```

```{r}
ggplot(AcuteOT) +
  geom_density(aes(Anaes_Span, fill = TOD)) +
  labs(title = "Density plot of acute case duration by time of the day June.2017", x = "Anaesthetic duration (minutes)") +
  guides(fill = guide_legend(title = "Time of Day")) +
  theme_minimal()
```

```{r}
AcuteProblem <- AcuteOT %>% 
  group_by(Problem_Description) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

AcuteProblem
```

```{r}

Nov17 <- read_csv("~/R-projects/Clinical_audits/Theatre/OTIS_Nov17.csv")

glimpse(Nov17)

```

```{r}
Nov17 <- Nov17 %>% 
  rename(Event_Date = 'Event Date', Operation__Description  = 'Operation Description', Speciality_Description = `Specialty Description`)

Nov17$Event_Date <-  dmy(Nov17$Event_Date)
Nov17$Theatre <- as.factor(Nov17$Theatre)

Nov17 <- Nov17 %>% 
  rename(Anaesthesia_Start = anaesthesia_start_datetime, Recovery_Takeover = recovery_takeover_datetime)

Nov17$Anaesthesia_Start <- dmy_hm(Nov17$Anaesthesia_Start)
Nov17$Recovery_Takeover <- dmy_hm(Nov17$Recovery_Takeover)


Nov17$Anaes_Span <- interval(Nov17$Anaesthesia_Start, Nov17$Recovery_Takeover)
Nov17$Anaes_Span <- as.duration(Nov17$Anaes_Span)
Nov17$Anaes_Span <- as.integer(Nov17$Anaes_Span)  / 60

Nov17 <- Nov17 %>% 
  filter(0 < Anaes_Span & Anaes_Span < 400)

Nov17$DOW <- wday(Nov17$Event_Date)
Nov17$Hour <- hour(Nov17$Anaesthesia_Start)
Nov17$Theatre <- as.factor(Nov17$Theatre)

Nov17$TOD <-  ifelse(8 <= Nov17$Hour & Nov17$Hour <= 17, "Daytime", "Afterhours" )
Nov17$TOD <- as.factor(Nov17$TOD)

glimpse(Nov17)

```

```{r}
OTIS17 <- Nov17

Nov17 <- Nov17 %>% 
  filter("2017-11-01" <= Event_Date & Event_Date <= "2017-11-30" & AdmissionType == "AC") %>% 
  filter(Theatre != "G", Theatre != "M", Theatre != "O", Theatre != "R", Theatre != "T")
```


```{r}
ggplot(data = Nov17) +
  geom_bar(aes(x = Theatre, fill = Theatre)) +
  labs(title = "Number of acute cases per theatre Nov.2017", x = "Theatre", y = "Count of Acute cases") +
  theme_minimal()
```

```{r}
ggplot(Nov17) +
  geom_histogram(aes(Anaes_Span, fill = TOD), binwidth = 10) +
  labs(title = "Density plot of Case duration by time of the day Nov.2017", x = "Anaesathetic duration (Minutes)") +
  guides(fill = guide_legend(title = "Time of Day")) +
  theme_minimal()
```


```{r}
ggplot(Nov17) +
  geom_density(aes(Anaes_Span, fill = TOD)) +
  labs(title = "Density plot of acute case duration by time of the day Nov.2017", x = "Anaesthetic duration (minutes)") +
  guides(fill = guide_legend(title = "Time of Day")) +
  theme_minimal()
```

```{r}

JuneDay <- AcuteOT %>% 
  filter(TOD == "Daytime")

JuneNight <-  AcuteOT %>% 
  filter(TOD == "Afterhours")

NovDay <- Nov17 %>% 
  filter(TOD == "Daytime")

NovNight <- Nov17 %>% 
  filter(TOD == "Afterhours")

mean(JuneDay$Anaes_Span, na.rm = TRUE)
mean(JuneNight$Anaes_Span, na.rm = TRUE)
mean(NovDay$Anaes_Span, na.rm = TRUE)
mean(NovNight$Anaes_Span, na.rm = TRUE)

t.test(JuneDay$Anaes_Span, JuneNight$Anaes_Span, paired = FALSE, var.equal = TRUE)

t.test(JuneDay$Anaes_Span, NovDay$Anaes_Span, paired = FALSE, var.equal = TRUE)
t.test(JuneNight$Anaes_Span, NovNight$Anaes_Span, paired = FALSE, var.equal = TRUE)

t.test(NovDay$Anaes_Span, NovNight$Anaes_Span, paired = FALSE, var.equal = TRUE)

```


```{r}
AcuteDay <- Nov17 %>% 
  filter(TOD == "Daytime") %>% 
  group_by(Operation__Description) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

kable(head(AcuteDay, n = 10), format = "html", caption = "Top ten types of acute operations during the day")
```


```{r}
AcuteNight <- Nov17 %>% 
  filter(TOD == "Afterhours") %>% 
  group_by(Operation__Description) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

kable(head(AcuteNight, n = 10), format = "html", caption = "Top ten types of after hours acute operations")
```

```{r}
JuneOG <- OTIS %>%
  filter(Specialty_Description == "Obstetrics" | Specialty_Description == "Gynaecology")

NovOG <- OTIS17 %>% 
  filter(Speciality_Description == "Obstetrics" | Speciality_Description == "Gynaecology")

JuneOT <- JuneOG %>% 
  filter("2017-06-01" <= Event_Date & Event_Date <= "2017-06-30") %>% 
  group_by(Specialty_Description, TOD) %>% 
  summarise(Count_June = n())

JuneOT <- JuneOT %>% 
  rename(Speciality_Description = Specialty_Description)

#JuneOT <- spread(JuneOT, TOD, Count_Day)

kable(JuneOT)

NovOT <- NovOG %>% 
  filter("2017-11-01" <= Event_Date & Event_Date <= "2017-11-30") %>% 
  group_by(Speciality_Description, TOD) %>% 
  summarise(Count_Nov = n())

#NovOT <-  spread(NovOT, TOD, Count_Night)

kable(NovOT)

UsageOT <- full_join(JuneOT, NovOT, by = c("Speciality_Description", "TOD"))
kable(UsageOT)

CrossTable(UsageOT$Count_June, UsageOT$Count_Nov, prop.r = FALSE, prop.c = FALSE, prop.chisq = FALSE, prop.t = FALSE, chisq = TRUE)
```

```{r}
#Histogram of acute case by day of week

ggplot(data = Nov17) +
  geom_bar(aes(x = DOW, fill = factor(DOW, labels = c("Sun", "Mon", "Tues", "Wed", "Thur", "Fri", "Sat")))) +
  labs(title = "Count of Acute cases by Day of Week, Nov.2017", x = "Day of week") +
  guides(fill = guide_legend(title = "Day of week")) +
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank())
```

```{r}
SubSpec_DOW <- Nov17 %>% 
  group_by(Speciality_Description, DOW) %>% 
  summarise(Count = n())

SubSpec_DOW <- spread(SubSpec_DOW, DOW, Count)
SubSpec_DOW <- SubSpec_DOW %>% 
  filter(Speciality_Description != "Gastroenterology" & Speciality_Description != "General Medicine" & Speciality_Description != "Pain Relief")

SubSpec_DOW
```

```{r}
SubSpec <- Nov17 %>% 
  group_by(Speciality_Description) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

kable(SubSpec)
```

